build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        APP_VERSION: $CI_COMMIT_TAG
  script:
    - go mod download
    - GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X 'main.Version=$APP_VERSION -o godeFmt ./cmd/godeFmt

