name: Go

on:
  release:
    types: [created]

jobs:
  patch-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get major version num and update tag
      run: |
        echo ": $GITHUB_REPOSITORY@$GITHUB_REF_NAME"
        echo ::set-env name=LD_FLAGS::"-X github.com/r-usenko/godeFmt.Version=$GITHUB_REF_NAME"
